[package]
name = "llvm_test"
version = "0.1.0"
authors = ["JunSuzukiJapan <jun.suzuki.japan@gmail.com>"]

[dependencies]
rustc-llvm-proxy = "0.1"

[dependencies.llvm-sys]
version = "60"
features = ["no-llvm-linking", "disable-alltargets-init"]
